/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_amirtuval_pighll_HyperLogLog */

#ifndef _Included_com_amirtuval_pighll_HyperLogLog
#define _Included_com_amirtuval_pighll_HyperLogLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_amirtuval_pighll_HyperLogLog
 * Method:    createHll
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_amirtuval_pighll_HyperLogLog_createHll
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_amirtuval_pighll_HyperLogLog
 * Method:    freeHll
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_amirtuval_pighll_HyperLogLog_freeHll
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
